---
parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    experimentalObjectRestSpread: true

env:
  browser: true
  jest: true
  jquery: true

rules:
  max-len:
    - error
    - code: 120
  import/no-named-as-default: 0
  react/forbid-prop-types:
    - error
    - forbid:
      - any
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  camelcase: 1
  no-unused-expressions:
    - error
    - allowTernary: true
extends: cerner
plugins:
  - react
  - jsx-a11y
  - import
globals:
  gon: true
  i18n: true
  mount: true
  mountWithIntl: true
  render: true
  shallow: true
  shallowWithIntl: true
  Terra: true
...
